name : first_ci/cd
on:
push:
branches:["main"]
pull_request:["main"]

workflow_dispatch:

jobs:
build:

runs-on:ubuntu-latest

steps:
	
uses:actions/checkout@v4

-name: Run a one-line script
run : echo Hello, world!

-name : Run a multiline script
run :|
echo aslema,
echo y hmama


